apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: jazinadia11/payment:latest
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: CONFIG_SERVER_URL
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://ms_pg_sql:5432/payment"
            - name: SPRING_DATASOURCE_USERNAME
              value: "nadia"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "nadia"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: shared-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_APPLICATION_CONFIGURATION_USER_URL
              value: "http://core:8060/api/v1"
