apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: jazinadia11/payment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              valueFrom:
                configMapKeyRef:
                  key: SPRING_KAFKA_BOOTSTRAP-SERVERS
                  name: payment-config
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: payment-config
            - name: SPRING_APPLICATION_CONFIGURATION_USER-URL
              valueFrom:
                configMapKeyRef:
                  key: CORE_SERVICE_URL
                  name: payment-config
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-payment
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-payment
                  key: SPRING_DATASOURCE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/payment"
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "kafka:9092"
  CORE_SERVICE_URL: "http://core:8060/api/v1"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-payment
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: bmFkaWE=
  SPRING_DATASOURCE_PASSWORD: bmFkaWE=