services:
  postgres:
    container_name: ms_pg_sql
    image: postgres:latest
    environment:
      POSTGRES_USER: nadia
      POSTGRES_PASSWORD: nadia
      POSTGRES_DB: payment
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - 5432:5432
    networks:
      - microservices-net
    restart: unless-stopped
  mysql:
    container_name: ms_my_sql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_USER: nadia
      MYSQL_PASSWORD: nadia
      MYSQL_DATABASE: notification
      MSDATA: /var/lib/mysql/data
    volumes:
      - mysql:/data/mysql
    ports:
      - 3308:3306
    networks:
      - microservices-net
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "news:1:3"
      KAFKA_OFFSETS_RETENTION_MINUTES: 60
    networks:
      microservices-net:



  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  mysql: