apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
data:
  CONFIG_SERVER_URL: "http://config-server:8888"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery:8761/eureka"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka.yml:9092"
