apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: bmFkaWE=
  SPRING_DATASOURCE_PASSWORD: bmFkaWE=
  SPRING_MAIL_USERNAME: bmFkaWE=
  SPRING_MAIL_PASSWORD: bmFkaWE=
  MYSQL_ROOT_PASSWORD: cm9vdC1wYXNzd29yZA==
