eureka:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761
spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: discovery