eureka:
  instance:
    hostname: payment
  client:
    service-url:
      defaultZone : http://localhost:8761/eurekaa
server:
  port: 8090
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: payment
    configuration:
      user-url: http://localhost:8060/api/v1
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment
    username: nadia
    password: nadia
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentConfirmation:com.example.aibouauth.payment.notification.PaymentNotificationRequest

