apiVersion: v1
kind: Service
metadata:
  name: maildev-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: maildev
  ports:
    - name: webui
      protocol: TCP
      port: 1080
      targetPort: 1080
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maildev
  template:
    metadata:
      labels:
        app: maildev
    spec:
      containers:
        - name: maildev
          image: maildev/maildev:latest
          ports:
            - containerPort: 1080
            - containerPort: 1025
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: maildev-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: maildev
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 1080
        - protocol: TCP
          port: 1025
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 1080
        - protocol: TCP
          port: 1025
