apiVersion: apps/v1
kind: Deployment
metadata:
  name: maildev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maildev
  template:
    metadata:
      labels:
        app: maildev
    spec:
      containers:
        - name: maildev
          image: maildev/maildev
          ports:
            - containerPort: 1025
            - containerPort: 1080
---
apiVersion: v1
kind: Service
metadata:
  name: maildev
spec:
  selector:
    app: maildev
  ports:
    - protocol: TCP
      port: 1025
      targetPort: 1025
    - protocol: TCP
      port: 1080
      targetPort: 1080
