apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BROKER_ID
                  name: kafka-configs
            - name: KAFKA_ZOOKEEPER_CONNECT
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_ZOOKEEPER_CONNECT
                  name: kafka-configs
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
                  name: kafka-configs
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_ADVERTISED_LISTENERS
                  name: kafka-configs
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
                  name: kafka-configs
            - name: KAFKA_CREATE_TOPICS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CREATE_TOPICS
                  name: kafka-configs
            - name: KAFKA_OFFSETS_RETENTION_MINUTES
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_OFFSETS_RETENTION_MINUTES
                  name: kafka-configs
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: kafka
    - protocol: TCP
      port: 29092
      targetPort: 29092
      name: kafka-internal
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configs
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_CREATE_TOPICS: "news:1:3"
  KAFKA_OFFSETS_RETENTION_MINUTES: "60"